config/routes.rb
Rails.application.routes.draw do


  resources :categories do
    resources :galleries do
      resources :photos
    end
  end

  get 'welcome/index'
  patch 'categories/:id/move_up', to: 'categories#move_up', as: 'category_move_up'
  patch 'categories/:id/move_down', to: 'categories#move_down', as: 'category_move_down'

  patch 'galleries/:id/move_up', to: 'galleries#move_up', as: 'gallery_move_up'
  patch 'galleries/:id/move_down', to: 'galleries#move_down', as: 'gallery_move_down'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :galleries, dependent: :destroy
  default_scope { order(order_idx: :asc) }
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :publicly_visible, -> { where(public: true) }

  def self.max_order_idx
    Category.maximum('order_idx')
  end

  def self.min_order_idx
    Category.minimum('order_idx')
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :category
  has_many :photos, dependent: :destroy
  default_scope { order(order_idx: :asc) }
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :publicly_visible, -> { where(public: true) }

  def self.max_order_idx(category_id)
    Gallery.where(category_id: category_id).maximum('order_idx')
  end

  def self.min_order_idx(category_id)
    Gallery.where(category_id: category_id).minimum('order_idx')
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  require 'paperclip'
  validates :image, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_categories

  def get_categories
    @menu_categories = Category.publicly_visible.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    @category.order_idx = Category.max_order_idx+1

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  def move_up
    category = Category.find(params[:id])
    prev_category = Category.where(order_idx: category.order_idx-1).first

    prev_category.order_idx = category.order_idx
    prev_category.save

    category.order_idx = category.order_idx-1
    category.save

    redirect_to categories_path
  end

  def move_down
    category = Category.find(params[:id])
    next_category = Category.where(order_idx: category.order_idx+1).first

    next_category.order_idx = category.order_idx
    next_category.save

    category.order_idx = category.order_idx+1
    category.save

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :public)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def show
    @category = Category.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @gallery = @category.galleries.new
  end

  def edit
    @category = Category.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])
  end

  def create
    @category = Category.find(params[:category_id])
    @gallery = @category.galleries.new(gallery_params)
    max_order_idx = Gallery.max_order_idx(@category)
    @gallery.order_idx = max_order_idx ? max_order_idx+1 : 0

    if @gallery.save
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])

    if @gallery.update(gallery_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @gallery = @category.galleries.find(params[:id])
    @gallery.destroy
    redirect_to category_path(@category)
  end

  def move_up
    gallery = Gallery.find(params[:id])
    prev_gallery = Gallery.where(category_id: gallery.category, order_idx: gallery.order_idx-1).first

    prev_gallery.order_idx = gallery.order_idx
    prev_gallery.save

    gallery.order_idx = gallery.order_idx-1
    gallery.save

    redirect_to category_path(gallery.category)
  end

  def move_down
    gallery = Gallery.find(params[:id])
    next_gallery = Gallery.where(category_id: gallery.category, order_idx: gallery.order_idx+1).first

    next_gallery.order_idx = gallery.order_idx
    next_gallery.save

    gallery.order_idx = gallery.order_idx+1
    gallery.save

    redirect_to category_path(gallery.category)
  end

  private
    def gallery_params
      params.require(:gallery).permit(:name, :public)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @gallery = Gallery.find(params[:gallery_id])
    @photo = @gallery.photos.new
  end

  def edit
    @category = Category.find(params[:category_id])
    @gallery = Gallery.find(params[:gallery_id])
    @photo = Photo.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @gallery = Gallery.find(params[:gallery_id])
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      redirect_to category_gallery_path(@gallery.category, @gallery)
    else
      render 'edit'
    end
  end

  def create
    @category = Category.find(params[:category_id])
    @gallery = Gallery.find(params[:gallery_id])
    @photo = @gallery.photos.new(photo_params)

    if @photo.save
      redirect_to category_gallery_path(@gallery.category, @gallery)
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @gallery = Gallery.find(params[:gallery_id])
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to category_gallery_path(@category, @gallery)
  end

  private

    def photo_params
      params.require(:photo).permit(:image, :caption, :public)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
    <% if @category.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@category.errors.count, 'error') %> prohibited this category from being saved:
          </h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :public %><br>
      <%= f.check_box :public, checked: true %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<%= link_to 'Back to Categories', categories_path %>

<h1> Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<%= link_to 'New Category', new_category_path %>

<h1> Categories </h1>

<table>
  <tr>
    <th>Name</th>
    <th colspan="2"></th>
    <th colspan="3"></th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td>
        <% unless category.public %>
            .
        <% end %>
        <%= category.name %>
      </td>
      <td><% if category.order_idx != Category.min_order_idx %><%= link_to 'Move Up', category_move_up_path(category), :method => :patch %><% end %></td>
      <td><% if category.order_idx != Category.max_order_idx %><%= link_to 'Move Down', category_move_down_path(category), :method => :patch %><% end %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Delete', category_path(category),
              method: :delete,
              data: {confirm: 'Ary you sure'} %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<%= link_to 'Back to Categories', categories_path %>

<h1> New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<%= link_to 'New Gallery', new_category_gallery_path(@category) %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back to Categories', categories_path %>

<p>
  <strong> Name:</strong>
  <%= @category.name %>
</p>

<h2>Galleries:</h2>
<table>
  <tr>
    <th>Name</th>
    <th colspan="2"></th>
    <th colspan="3"></th>
  </tr>
  <%= render @category.galleries %>
</table>

app/views/galleries/_form.html.erb
<%= form_for([@category, @gallery]) do |f| %>
    <% if @gallery.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@gallery.errors.count, 'error') %> prohibited this category from being saved:
          </h2>
          <ul>
            <% @gallery.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :public %><br>
      <%= f.check_box :public, checked: true %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/galleries/_gallery.html.erb
<tr>
  <td>
    <% unless gallery.public %>
        .
    <% end %>
    <%= gallery.name %></td>
  <td>
    <% if gallery.order_idx != Gallery.min_order_idx(gallery.category) %>
      <%= link_to 'Move Up', gallery_move_up_path(gallery), :method => :patch %>
    <% end %>
  </td>
  <td>
    <% if gallery.order_idx != Gallery.max_order_idx(gallery.category) %>
      <%= link_to 'Move Down', gallery_move_down_path(gallery), :method => :patch %>
    <% end %>
  </td>
  <td><%= link_to 'Show', category_gallery_path(gallery.category, gallery) %></td>
  <td><%= link_to 'Edit', edit_category_gallery_path(gallery.category, gallery) %></td>
  <td>
    <%= link_to 'Delete', [gallery.category, gallery],
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/galleries/edit.html.erb
<%= link_to 'Back to ' + @category.name, category_path(@category) %>

<h1> Edit Gallery</h1>

<%= render 'form' %>

app/views/galleries/new.html.erb
<%= link_to 'Back to ' + @category.name, category_path(@category) %>

<h1> New Gallery</h1>

<%= render 'form' %>

app/views/galleries/show.html.erb
<%= link_to 'Add Photo', new_category_gallery_photo_path(@gallery.category, @gallery)  %>
<%= link_to 'Back to ' + @gallery.category.name, category_path(@gallery.category) %>

<div id='gallery'>
  <p>
    <strong> Name:</strong>
    <%= @gallery.name %>
  </p>

  <% @gallery.photos.each do |photo| %>
      <div id="caption">
        <% unless photo.public %>
            .
        <% end %>
        <%= photo.caption %>
        <%= link_to 'Edit', edit_category_gallery_photo_path(@category, @gallery, photo) %>
        <%= link_to 'Delete', category_gallery_photo_path(@category, @gallery, photo),
                    method: :delete,
                    data: {confirm: 'Ary you sure'} %>
      </div>
      <%= image_tag photo.image.url(:medium) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotographySite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <div id="header">
        <h1>Julie Anne Moore</h1>

        <nav>
          <%= link_to "HOME", root_path %>
          <% @menu_categories.each do |category| %>
            <div class="dropdown">
              <%= link_to category.name.upcase, category_path(category), :class=>'dropbtn' %>
              <div class="dropdown-content">
                <% category.galleries.publicly_visible.each do |gallery| %>
                    <%= link_to gallery.name.upcase, category_gallery_path(gallery.category, gallery) %>
                <% end %>
              </div>
            </div>
          <% end %>
        </nav>
      </div>
      <div id="content">
        <%= yield %>
      </div>

      <div id="footer" >
        <br>
        <br>
        <br>
        <br>
        <br>
        <p>&#169;2016 by Julie Anne Moore. Site proudly designed by Julie Anne Moore.</p>
        <div>
          <a class="btn btn-social-icon btn-flickr" href="http://www.flickr.com/photos/29878460@N07/">
            <i class="fa fa-flickr"></i>
          </a>
          <a class="btn btn-social-icon btn-instagram" href="http://www.instagram.com/jamoore20/">
            <i class="fa fa-instagram"></i>
          </a>
          <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/Infinity.Pet.Photography/">
            <i class="fa fa-facebook"></i>
          </a>
          <a class="btn btn-social-icon btn-deviantart" href="http://landofstandardbreds.deviantart.com/">
            <i class="fa fa-deviantart"></i>
          </a>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for([@category, @gallery, @photo]) do |f| %>
    <% if @photo.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@photo.errors.count, 'error') %> prohibited this category from being saved:
          </h2>
          <ul>
            <% @photo.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.file_field :image %>
    </p>

    <p>
      <%= f.label :caption %><br>
      <%= f.text_field :caption %>
    </p>

    <p>
      <%= f.label :public %><br>
      <%= f.check_box :public %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/photos/edit.html.erb
<%= link_to 'Back to ' + @gallery.name, category_gallery_path(@gallery.category, @gallery) %>

<h1> Edit Photo</h1>

<%= render 'form' %>

app/views/photos/new.html.erb
<%= link_to 'Back to ' + @gallery.name, category_gallery_path(@gallery.category, @gallery) %>

<h1> New Photo</h1>

<%= render 'form' %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>This page is under construction. Try again later.</p>